#ifndef LGNOME_UI_PRECONNECT_SCREEN_H
#define LGNOME_UI_PRECONNECT_SCREEN_H

typedef enum NativeUiScreenId {
    NATIVE_UI_SCREEN_HUB = 0,
    NATIVE_UI_SCREEN_SETUP,
    NATIVE_UI_SCREEN_CAPTURE,
    NATIVE_UI_SCREEN_ONBOARDING,
    NATIVE_UI_SCREEN_COUNT,
} NativeUiScreenId;

#endif
